concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "all"
  url = "https://gitlab.local.jarand.site"
  id = 12
  token = ""
  token_obtained_at = 2024-06-17T20:30:46Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:dind"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache"]
    shm_size = 0

[runners.docker.registry]
  insecure = true
  url = "http://gitlab.dockerhost.home:5000"
  concurrent = 1
  check_interval = 0
  shutdown_timeout = 0